name: Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
    name: Java ${{ matrix.Java }} Check

    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
    - name: Install Gradle
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install gradle 8.3
      shell: bash
    - name: Test
      run: |
        cd library && gradle check --stacktrace && gradle publishToMavenLocal
        cd ../plugin && gradle check --stacktrace && gradle publishToMavenLocal
        cd ../rpg && gradle check --stacktrace
